package com.co3.servlets;

import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Experiment 6: Basic Java Servlet for Dynamic Content Generation
 * 
 * Objectives:
 * - Extend HttpServlet and override doGet()
 * - Access HttpServletRequest and HttpServletResponse
 * - Generate dynamic HTML response using PrintWriter
 * - Display welcome message, student name, course name, and live server timestamp
 */
@WebServlet(name = "Exp6DynamicContentServlet", urlPatterns = {"/exp6", "/welcome"})
public class Exp6DynamicContentServlet extends HttpServlet {

    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) 
            throws ServletException, IOException {
        
        // 1. Set response content type to HTML with UTF-8 encoding
        response.setContentType("text/html;charset=UTF-8");

        // 2. Extract query parameters (optional overrides or default values)
        String studentName = request.getParameter("name");
        if (studentName == null || studentName.trim().isEmpty()) {
            studentName = "Alex Johnson (Reg: 21CS101)";
        }

        String courseName = request.getParameter("course");
        if (courseName == null || courseName.trim().isEmpty()) {
            courseName = "CS8381 - Web Technology & Java Enterprise Applications";
        }

        // 3. Compute dynamic date and time on the server
        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEEE, MMMM dd, yyyy 'at' hh:mm:ss a");
        String formattedDateTime = now.format(formatter);

        // 4. Output dynamic HTML stream using PrintWriter
        try (PrintWriter out = response.getWriter()) {
            out.println("<!DOCTYPE html>");
            out.println("<html lang='en'>");
            out.println("<head>");
            out.println("    <meta charset='UTF-8'>");
            out.println("    <meta name='viewport' content='width=device-width, initial-scale=1.0'>");
            out.println("    <title>Experiment 6: Dynamic Content Generation Servlet</title>");
            out.println("    <style>");
            out.println("        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f1f5f9; color: #0f172a; padding: 2rem; }");
            out.println("        .container { max-width: 800px; margin: 0 auto; background: #ffffff; border-radius: 12px; padding: 2.5rem; box-shadow: 0 10px 25px -5px rgba(0,0,0,0.08); border: 1px solid #e2e8f0; }");
            out.println("        .badge { display: inline-block; background: #dcfce7; color: #15803d; padding: 4px 12px; border-radius: 20px; font-weight: 600; font-size: 0.85rem; margin-bottom: 1rem; }");
            out.println("        h1 { color: #1e293b; margin-bottom: 0.5rem; font-size: 1.75rem; }");
            out.println("        .tagline { color: #64748b; font-size: 0.95rem; margin-bottom: 2rem; }");
            out.println("        .info-card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 1.5rem; margin-bottom: 1.5rem; }");
            out.println("        .info-row { display: flex; justify-content: space-between; padding: 0.75rem 0; border-bottom: 1px dashed #cbd5e1; }");
            out.println("        .info-row:last-child { border-bottom: none; }");
            out.println("        .label { font-weight: 600; color: #475569; }");
            out.println("        .value { font-weight: 700; color: #2563eb; }");
            out.println("        .time-box { background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 8px; padding: 1rem; text-align: center; font-size: 1.1rem; color: #1d4ed8; font-weight: 600; }");
            out.println("        .footer-note { font-size: 0.8rem; color: #94a3b8; text-align: center; margin-top: 2rem; }");
            out.println("    </style>");
            out.println("</head>");
            out.println("<body>");
            out.println("    <div class='container'>");
            out.println("        <span class='badge'>Java Servlet 3.1+ Dynamic Response</span>");
            out.println("        <h1>👋 Welcome to Course Outcome 3 (CO3)</h1>");
            out.println("        <p class='tagline'>Dynamically generated by <code>Exp6DynamicContentServlet</code> running on Apache Tomcat.</p>");
            out.println("        <div class='info-card'>");
            out.println("            <div class='info-row'><span class='label'>Student Name:</span> <span class='value'>" + studentName + "</span></div>");
            out.println("            <div class='info-row'><span class='label'>Course Title:</span> <span class='value'>" + courseName + "</span></div>");
            out.println("            <div class='info-row'><span class='label'>Protocol:</span> <span class='value'>" + request.getProtocol() + "</span></div>");
            out.println("            <div class='info-row'><span class='label'>Client IP Address:</span> <span class='value'>" + request.getRemoteAddr() + "</span></div>");
            out.println("        </div>");
            out.println("        <div class='time-box'>");
            out.println("            🕒 Live Server Timestamp: " + formattedDateTime);
            out.println("        </div>");
            out.println("        <p class='footer-note'>Hit refresh to observe real-time dynamic timestamp regeneration by the servlet container.</p>");
            out.println("    </div>");
            out.println("</body>");
            out.println("</html>");
        }
    }
}
